namespace Compilador.Transversal
{
    public enum Categoria
    {
        //SUMA, RESTA, MULTIPLICACION, DIVISION, MAYOR_QUE, MENOR_QUE, ENTERO, MODULO, PARENTESIS_ABRE, PARENTESIS_CIERRA, EOF, NUMERO_DECIMAL, IDENTIFICADOR, IGUAL_QUE, DIFERENTE_QUE, MENOR_IGUAL_QUE, MAYOR_IGUAL_QUE, ASIGNACION, CARACTER_NO_VALIDO,

        VARIABLE, VALOR_RETORNO, VALOR_ENVIO, SEPARADOR, IN, OUT, ON, OFF, UP, DOWN, KELVIN, CENTIGRADOS, GET, START, STATUS, SHUTDOWN, SUCCESS, RESTART, FAIL, RANKINE, FARENHEIT, EOF, CARACTER_NO_VALIDO, PALABRA_RESERVADA_ON, PALABRA_RESERVADA_OFF, PALABRA_RESERVADA_SHUTDOWN

    }
}
