namespace Compilador.Transversal
{
    public enum Categoria
    {
       
        VARIABLE, VALOR_RETORNO, VALOR_ENVIO, SEPARADOR, IN, OUT, ON, OFF, UP, DOWN, KELVIN, CENTIGRADOS, GET, START, STATUS, SHUTDOWN, SUCCESS, RESTART, FAIL, RANKINE, FARENHEIT, EOF, CARACTER_NO_VALIDO, 
        
        PALABRA_RESERVADA_IN, PALABRA_RESERVADA_OUT, PALABRA_RESERVADA_ON, PALABRA_RESERVADA_OFF, PALABRA_RESERVADA_UP, PALABRA_RESERVADA_DOWN, PALABRA_RESERVADA_KEVIN, PALABRA_RESERVADA_CENTIGRADOS, PALABRA_RESERVADA_GET, PALABRA_RESERVADA_START, PALABRA_RESERVADA_SHUTDOWN, PALABRA_RESERVADA_SUCCESS, PALABRA_RESERVADA_RESTART, PALABRA_RESERVADA_FAIL,
        PALABRA_RESERVADA_RANKINE, PALABRA_RESERVADA_FARENHEIT, PALABRA_RESERVADA_EOF, PALABRA_RESERVADA_STATUS, PALABRA_RESERVADA_KELVIN

    }
}
